config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  ## Root Path
  root to: 'welcome#index'

  ## Devise Authentication 
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks'
  }

  ## ------------------------------------------------------------------------------
  ## Organizations
  ## ------------------------------------------------------------------------------

  resources :organizations do
  	collection do
  		get :getOrganization
  	end
  end

  ## ------------------------------------------------------------------------------
  ## User Routes
  ## ------------------------------------------------------------------------------

  resources :users do
    collection do
      ## Non Authentication Routes
      get :getUser
      get :existUser
      get :lockUser
      get :profile
      get :getPassword
      get :creditCardValidation
      get :lock_screen
    end
  end

  resources :invitations do
    collection do
      get :existMember
      get :accept
      get :thank_you
      post :accept_invitation
    end
  end

  resources :projects do
    collection do
      get :getProNameUniq ## Get Uniq Project Name
    end
    member do
      post :invitation
    end
    resources :clients, except: [:index]
  end

  ## Dashboard Routes
  get '/dashboard' => 'users#dashboard', as: :user_dashboard
  get '/admin/dashboard' => 'admin#dashboard', as: :admin_dashboard

  ## ------------------------------------------------------------------------------
  ## Secure Routes
  ## ------------------------------------------------------------------------------
  namespace :secure do
    resources :projects do
      resources :tasks do
        collection do 
          post :store_attachments
        end
        member do
          get :subtask
        end
        resources :task_attachments, only: [:destroy] do
          get :download
        end

        resources :assigns, only: [:new, :create]
        resources :watchers, only: [:create, :new]
      end
      member do
        get :reports
        resources :agile_boards, only: [:index] do
          collection do
            post :add_task
          end
        end
      end
      resources :comments, except: [:index, :show]
    end    
  end

  ## ------------------------------------------------------------------------------
  ## HR department
  ## ------------------------------------------------------------------------------
  
  resources :holidays do
    collection do
      get :getExistHoliday
      get :import
      get :calendar
      post :import_holiday
    end
  end

  resources :employees do
    collection do
      put :employee_document_update
    end
    resources :employee_documents, only: [:destroy] do
      get :download
    end
  end

  resources :letters do
    member do
      get :generate_pdf
      patch :download_pdf
      get :pdf_viewer      
    end
    collection do
      post :user_info
    end
  end

  ## ------------------------------------------------------------------------------
  ## Admin Routes
  ## ------------------------------------------------------------------------------

  namespace :admin do
    resources :organizations
    
    resources :plans do
      collection do
        get 'getPlan'
      end
    end

    resources :transactions, only: [:index, :show]
  end

  ## Non Authenticate Routes for authorize silent post
  post '/transactions/authorize_silent_post' => 'transactions#authorize_silent_post'
  get '/thank-you' => 'welcome#thank_you', as: :thank_you
end

app/models/holiday.rb
# == Schema Information
#
# Table name: holidays
#
#  id              :integer          not null, primary key
#  name            :string
#  hdate           :date
#  htype           :integer
#  organization_id :integer
#  archive         :boolean
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Holiday < ApplicationRecord
	## Relationships
	belongs_to :organization

	## Validations
	validates :name, :hdate, :htype, presence: true

	## Attr Accessor
	attr_accessor :import_by, :file

	## scopes
	scope :nationals, -> {where('htype = ?', 1)}
	scope :generals, -> {where('htype = ?', 2)}

	## Method
	def holiday_type
		Rails.application.secrets.holiday_type[self.htype.to_i]
	end

	def uniq_number
		unumber = "#{id}".rjust(4, '0')
		"HLD0#{created_at.to_i}#{unumber}"
	end

end

app/controllers/holidays_controller.rb
require 'csv'
class HolidaysController < MainController

	skip_before_action :verify_authenticity_token, only: [:import_holiday]

	expose :holidays, ->{ @current_organization.holidays }
	expose :holiday

  add_breadcrumb 'Home', :user_dashboard_path
  add_breadcrumb 'Holiday', :holidays_path
	
	def create
		holiday = @current_organization.holidays.build(holiday_params)
		holiday.save if holiday.valid?
		respond_to do |format|
			format.html{redirect_to hr_holidays_path, notice: 'Successfully added holiday for your organization!'}
			format.js
		end
	end

	def edit
		respond_to do |format|
			format.html{ redirect_to hr_holidays_path }
			format.js
		end
	end

	def update
		holiday.update(holiday_params)
		respond_to do |format|
			format.html{ redirect_to hr_holidays_path, notice: 'Successfully updated holiday!' }
			format.js
		end		
	end

	def destroy
		holiday.destroy if holiday.present?
  	respond_to do |format|
  		format.html{
  			redirect_to hr_holidays_path, flash: {notice: 'Successfully deleted holiday !'}
  		}
  		format.json{
  			render json: {id: holiday.uniq_number, total: @current_organization.holidays.count, url: '/holidays'}, status: 200
  		}
  	end		
	end

	def import
		respond_to do |format|
			format.html{ redirect_to hr_holidays_path }
			format.js
		end
	end

	def import_holiday
		case params[:holiday][:import_by].to_s
		when '1' ## All Saturday Off
			all_saturday_off
		when '2', '3' ## 1st, 3rd and 5th Saturday off			
			custom_saturday_off(params[:holiday][:import_by].to_s)
		when '4' ## Custom File Upload
			@error = custom_holiday_upload(params[:holiday][:file])
		end
		respond_to do |format|
			format.html{ redirect_to hr_holidays_path }
			format.js
		end		
	end

	def calendar
		holiday_list = []
		@current_organization.holidays.select('id, name, hdate').each do |holiday|
			holiday_list << {title: holiday.name, start: holiday.hdate.to_date.to_s, allDay: true}
		end
		gon.holiday_list = holiday_list
	end

	def getExistHoliday
		if params[:id].present?
    	holidays = @current_organization.holidays.where('DATE(hdate) = ? and id != ?', params[:holiday][:hdate].to_date, params[:id])
    else
    	holidays = @current_organization.holidays.where('DATE(hdate) = ?', params[:holiday][:hdate].to_date)
    end
    render json: holidays.present? ? false : true		
	end

	private

	def holiday_params
		params.require(:holiday).permit(:name, :hdate, :htype, :import_by, :file)
	end

	def all_saturday_off
		start_date 	= "1/1/#{Date.today.year}".to_date
		end_date 		= "31/12/#{Date.today.year}".to_date
		result 	= (start_date..end_date).to_a.select {|k| [6].include?(k.wday)}
		result.each do |sat|
			find_or_create_holiday(sat)
		end
	end

	def custom_holiday_upload(file)		
		error = nil
		if file.content_type == 'text/csv'
			CSV.foreach(file.path, :headers => true) do |row|
				begin
					find_or_create_holiday(row['holiday_date'])
				rescue => e
					error = e
				end
			end
		else
			error = 'Invalid file format'
		end		
	end

	def custom_saturday_off(imtype)
		start_date = "1/1/#{Date.today.year}".to_date
		end_date = "31/12/#{Date.today.year}".to_date
		result 	= (start_date..end_date).to_a.select {|k| [6].include?(k.wday)}
		result.group_by{|mon| mon.month}.each do |month, sats|
			sats.each_with_index do |sat, index|
				index += 1
				case imtype.to_s
				when '2'
					find_or_create_holiday(sat) if index%2 != 0
				when '3'					
					find_or_create_holiday(sat) if index%2 == 0
				end
			end
		end		
	end

	def find_or_create_holiday(sat)
		hld = @current_organization.holidays.where('DATE(hdate) = ?', sat.to_date)
		if !hld.present?
			@current_organization.holidays.create(hdate: sat.to_date, name: 'Saturday Off', htype: 2)
		end
	end
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/views/holidays/_form.html.erb
<div class='modal inmodal' id='edit-hr-holiday-popup' tabindex='-1' role='dialog' aria-hidden='true'>
  <div class='modal-dialog'>
    <div class='modal-content animated bounceInRight'>
      <div class='modal-header'>
        <button type='button' class='close' data-dismiss='modal'><span aria-hidden='true'>&times;</span><span class='sr-only'>Close</span></button>
        <h4 class='modal-title'>
          <i class="fa fa-globe"></i>
          Edit Holiday
        </h4>
      </div>
      
      <%= nested_form_for holiday, html: {class: 'form-horizontal edit-hr-holiday-form'}, remote: true do |form| %>
        <div class='modal-body'>

          <div class="form-group">
            <%= form.label :htype, 'Type of Holiday', class: 'col-sm-3 control-label' %>
            <div class="col-sm-9">
              <%= form.select :htype, options_for_select(Rails.application.secrets.holiday_type.invert.to_a, form.object.htype), {include_blank: 'Select Type'}, {class: 'form-control'} %>
            </div>
          </div>

          <div class="form-group">
            <%= form.label :name, 'Holiday Name', class: 'col-sm-3 control-label' %>
            <div class="col-sm-9">
              <%= form.text_field :name, placeholder: 'Holiday Name', class: 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <%= form.label :hdate, 'Holiday Date', class: 'col-sm-3 control-label' %>
            <div class="col-sm-5">
              <%= form.text_field :hdate, value: form.object.hdate.strftime('%d/%m/%Y'), class: 'form-control holiday-date', placeholder: 'DD/MM/YYYY' %>
            </div>
          </div>

        </div>

        <div class='modal-footer'>          
          <button type='submit' class='btn btn-primary m-b-2' data-disable-with="<%= loader %>">Update Holiday</button>
          <button type='button' class='btn btn-white m-b' data-dismiss='modal'>Close</button>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/holidays/_import.html.erb
<div class='modal inmodal' id='edit-hr-holiday-popup' tabindex='-1' role='dialog' aria-hidden='true'>
  <div class='modal-dialog'>
    <div class='modal-content animated bounceInRight'>
      <div class='modal-header'>
        <button type='button' class='close' data-dismiss='modal'><span aria-hidden='true'>&times;</span><span class='sr-only'>Close</span></button>
        <h4 class='modal-title'>
          <i class="fa fa-globe"></i>
          Import Holidays
        </h4>
      </div>
      
      <%= form_for holiday, url: {controller: 'holidays', action: 'import_holiday'}, method: :post, html: {class: 'form-horizontal edit-hr-holiday-form'}, remote: true do |form| %>
        <div class='modal-body'>

          <div class="form-group">                        
            <div class="col-sm-6">              
              <div class="i-checks">
                <label>                  
                  <%= form.radio_button :import_by, 1, class: 'import_by' %>
                  <i></i> All Saturday Off
                </label>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="i-checks">
                <label>
                  <%= form.radio_button :import_by, 2, class: 'import_by' %>
                  <i></i> 1st , 3rd and 5th Saturday Off
                </label>
              </div>
            </div>
            <br/><br/>
            <div class="col-sm-6">
              <div class="i-checks">
                <label>
                  <%= form.radio_button :import_by, 3, class: 'import_by' %>
                  <i></i> 2nd and 4th Saturday Off
                </label>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="i-checks">
                <label>
                  <%= form.radio_button :import_by, 4, checked: true, class: 'import_by' %>
                  <i></i> Import from file (Only CSV)
                </label>
              </div>
            </div>            
          </div>

          <div class="form-group import-hld-section">
            <%= form.label :file, 'Upload File', class: 'col-sm-3 control-label' %>
            <div class="col-sm-9">
              <div class="fileinput fileinput-new" data-provides="fileinput">
                <span class="btn btn-default btn-file">
                  <span class="fileinput-new">Select file</span>
                  <span class="fileinput-exists">Change</span>                  
                  <%= form.file_field :file, class: 'required', accept: ".csv" %>
                </span>
                <span class="fileinput-filename"></span>
                <a href="#" class="close fileinput-exists" data-dismiss="fileinput" style="float: none">×</a>
              </div>
              <div class="clearfix"></div>
              <span>
                Only CSV file supported. <%= link_to 'Download Format', '/holidays.csv' %> <br/>
                <small>
                  Note: <br/>
                  <ol>
                    <li>
                      holiday_type : 1 for National Holiday and 2 for General Holiday
                    </li>
                    <li>
                      holiday_date : Format must be : DD/MM/YYYY
                    </li>
                  </ol>
                </small>
              </span>
            </div>
          </div>

        </div>

        <div class='modal-footer'>          
          <button type='submit' class='btn btn-primary m-b-2' data-disable-with="<%= loader %>">Add Holidays</button>
          <button type='button' class='btn btn-white m-b' data-dismiss='modal'>Close</button>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/holidays/_list.html.erb
<div id='edit-hr-holiday'></div>
<% if holidays.present? %>
	<div class="panel-heading">
	  <div class="panel-options">
	    <ul class="nav nav-tabs">
	      <li class="active">
	      	<a href="#nation-tab-1" data-toggle="tab" aria-expanded="true">National Holidays</a>
	      </li>
	      <li class="">
	      	<a href="#general-tab-2" data-toggle="tab" aria-expanded="false">General Holidays</a>
	      </li>
	    </ul>
	  </div>	  
	</div>
	<div class="panel-body padtop0">
		<div class="tab-content">
			<div class="tab-pane active" id="nation-tab-1">
				<% if holidays.nationals.present? %>
					<table class="table table-hover">
				    <thead>
				      <tr>
				        <th>Holiday Name</th>
				        <th>Date</th>		        
				        <th></th>
				      </tr>
				    </thead>
				    <tbody>
			      	<% holidays.nationals.each do |holiday| %>
			      		<%= render partial: '/holidays/table', locals: {holiday: holiday} %>
				      <% end %>
				    </tbody>
				  </table>
				<% else %>
					<p>No Holiday Found </p>
				<% end %>
			</div>
			<div class="tab-pane" id="general-tab-2">
				<% if holidays.generals.present? %>
					<table class="table table-hover">
				    <thead>
				      <tr>
				        <th>Holiday Name</th>
				        <th>Date</th>
				        <th></th>
				      </tr>
				    </thead>
				    <tbody>
				    	<% holidays.generals.group_by{|hld| hld.hdate.month }.each do |month, hldays| %>
				      	<tr>
				      		<td colspan='3'>
				      			<strong><%= Date::MONTHNAMES[month] %> <%= Date.today.year %></strong>
				      		</td>
				      	</tr>
				      	<% hldays.each do |holiday| %>
									<%= render partial: '/holidays/table', locals: {holiday: holiday} %>
					      <% end %>
				    	<% end %>
				    </tbody>
				  </table>
				<% else %>
					<p> No Holiday Found </p>
				<% end %>
			</div>
		</div>
	</div>
<% else %>
	<div class="panel-heading">
	  <div class="panel-options">
	  	<p>No Holiday Found !</p>
	 	</div>
	</div>
<% end %>

app/views/holidays/_table.html.erb
<tr id='<%= holiday.uniq_number %>' class='<%= holiday.holiday_type.downcase %>-holidays'>
  <td class='col-lg-9'><%= holiday.name %></td>
  <td><%= holiday.hdate.strftime('%d/%m/%Y') %></td>
  <td>
  	<% if is_hr_access? && holiday.hdate >= Time.zone.now.to_date %>
  		<%= link_to "<i class='fa fa-pencil'></i>".html_safe, edit_holiday_path(holiday), class: 'btn btn-xs btn-default', data: {disable_with: icon_loader, remote: true} %>
  		<%= link_to "<i class='fa fa-trash'></i>".html_safe, 'javascript:void(0);', class: 'btn btn-xs btn-danger', data: {behavior: 'holiday-delete', href: holiday_path(holiday)} %>
  	<% end %>
  </td>
</tr>

app/views/holidays/calendar.html.erb
<% content_for :title, "Calendar" %>
<div class='row wrapper border-bottom white-bg page-heading'>
  <div class='col-sm-6'>
    <%= show_breadcrumb('Holidays : Calendar View') %>
  </div>
  <div class="col-sm-6 text-right">
    <h2>
      <%= link_to 'Back', holidays_path, data: {disable_with: loader}, class: 'btn btn-primary btn-xs' %>
    </h2>
  </div>
</div>

<div class='row'>
	<div class='col-lg-12 pad0'>
  	<div class='wrapper wrapper-content animated fadeInUp'>
      <div class='ibox'>
        <div class='ibox-content'>
					 <div id="holiday-calendar"></div>         
        </div>
      </div>
    </div>
 	</div>
</div>

app/views/holidays/create.js.erb
$("#new_holiday")[0].reset();
$(".list-of-holidays").html("<%= escape_javascript(render partial: '/holidays/list') %>")
$.getScript('/assets/hr/holidays.js')

app/views/holidays/edit.js.erb
$('#edit-hr-holiday').html("<%= escape_javascript(render partial: '/holidays/form') %>")
$('#edit-hr-holiday-popup').modal({backdrop: 'static', keyboard: false})

$.getScript('/assets/hr/holidays.js')

var dateToday = new Date();
$('.holiday-date').datepicker({
  autoclose: true,  
  startDate: '-1d',
  daysOfWeekDisabled: '0',
  format: "dd/mm/yyyy"
})


$('.edit-hr-holiday-form').validate({
	rules: {
		'holiday[name]': {
			required: true,
		},
		'holiday[hdate]': {
			required: true,
			remote: {
				type: 'get',
				url: '/holidays/getExistHoliday',
				data: {id: '<%= holiday.id %>'},
				dataType: 'json'
			}				
		},
		'holiday[htype]': {
			required: true
		}
	},
	messages: {
		'holiday[name]': {
			required: "Name can't be blank!"				
		},
		'holiday[hdate]': {
			required: "Date can't be blank!",
			remote: 'Already added for this date!'
		},
		'holiday[htype]': {
			required: "Type can't be blank!"
		}
	}
})

app/views/holidays/import.js.erb
$('#edit-hr-holiday').html("<%= escape_javascript(render partial: '/holidays/import') %>")
$('#edit-hr-holiday-popup').modal({backdrop: 'static', keyboard: false})

$('.i-checks').iCheck({  
  radioClass: 'iradio_square-green',
});


$('input:radio').on('ifChecked', function(event){ 
	if($(this).val() == '4'){
		$("#holiday_file").addClass('required');
		$(".import-hld-section").removeClass('hide');
	}else{
		$("#holiday_file").removeClass('required');
		$(".import-hld-section").addClass('hide');
	}	
});

$("#new_holiday").validate()

app/views/holidays/import_holiday.js.erb
<% if @error.present? %>
  toastr.error('<%= @error %>')
<% else %>
  toastr.success('Successfully imported holidays.')

	$('#edit-hr-holiday-popup').modal('hide');
	$(".list-of-holidays").html("<%= escape_javascript(render partial: '/holidays/list') %>")

	$.getScript('/assets/hr/holidays.js')
<% end %>

app/views/holidays/index.html.erb
<% content_for :title, "Holiday List" %>
<div class='row wrapper border-bottom white-bg page-heading'>
  <div class='col-sm-6'>
    <%= show_breadcrumb('Holidays') %>
  </div>
</div>

<div class='row holidays-list'>
	<div class="<%= is_hr_access? ? 'col-lg-8' : 'col-lg-12' %> padrgt0">
  	<div class='wrapper wrapper-content animated fadeInUp h-list'>
      <div class='ibox'>
        <div class='ibox-title'>
          <h5>All holidays associated to this organization</h5>
          <div class='new-project-popup'></div>
          <div class='ibox-tools'>
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false">
              <i class="fa fa-wrench"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
              <% if is_hr_access? %>
                <li><%= link_to 'Import Holidays', import_holidays_path, data: {disable_with: loader, remote: true} %></li>
              <% end %>
              <li><%= link_to 'View Calendar', calendar_holidays_path, data: {disable_with: loader} %></li>
            </ul>
          </div>
        </div>        
        <div class='ibox-content list-of-holidays'>
          <%= render partial: '/holidays/list' %>          
        </div>
      </div>
    </div>
 	</div>
  <% if is_hr_access? %>
    <div class='col-lg-4 padlft0'>
      <div class='wrapper wrapper-content animated fadeInUp'>
        <div class='ibox'>
          <div class='ibox-title'>
            <h5>Add Holiday</h5>
          </div>        
          <div class='ibox-content'>

            <%= form_for holiday, html: { class: 'new-project-client-page' }, remote: true do |form| %>
                            
              <div class="form-group">
                <%= form.label :name, 'Holiday Name'%>
                <%= form.text_field :name, placeholder: 'Holiday Name', class: 'form-control' %>
              </div>

              <div class='form-group'>
                <%= form.label :hdate, 'Holiday Date'%>                            
                <%= form.text_field :hdate, class: 'form-control holiday-date', placeholder: 'DD/MM/YYYY' %>
              </div>  

              <div class="form-group">
                <%= form.label :htype, 'Type of Holiday'%>
                <%= form.select :htype, options_for_select(Rails.application.secrets.holiday_type.invert.to_a), {include_blank: 'Select Type'}, {class: 'form-control'} %>
              </div>

              <div class="hr-line-dashed"></div>
              <%= button_tag 'Add Holiday', class: 'btn btn-primary', data: { disable_with: loader} %>            
            <% end %>

          </div>
        </div>
      </div>
    </div> 
  <% end %>
</div>

app/views/holidays/update.js.erb
$.getScript('/assets/hr/holidays.js')
$('#edit-hr-holiday-popup').modal('hide');
$(".list-of-holidays").html("<%= escape_javascript(render partial: '/holidays/list') %>")

toastr.success('Holiday has been updated.')