config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  ## Root Path
  root to: 'welcome#index'

  ## Devise Authentication 
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks'
  }

  ## ------------------------------------------------------------------------------
  ## Organizations
  ## ------------------------------------------------------------------------------

  resources :organizations do
  	collection do
  		get :getOrganization
  	end
  end

  ## ------------------------------------------------------------------------------
  ## User Routes
  ## ------------------------------------------------------------------------------

  resources :users do
    collection do
      ## Non Authentication Routes
      get :getUser
      get :existUser
      get :lockUser
      get :profile
      get :getPassword
      get :creditCardValidation
      get :lock_screen
    end
  end

  resources :invitations do
    collection do
      get :existMember
      get :accept
      get :thank_you
      post :accept_invitation
    end
  end

  resources :projects do
    collection do
      get :getProNameUniq ## Get Uniq Project Name
    end
    member do
      post :invitation
    end
    resources :clients, except: [:index]
  end

  ## Dashboard Routes
  get '/dashboard' => 'users#dashboard', as: :user_dashboard
  get '/admin/dashboard' => 'admin#dashboard', as: :admin_dashboard

  ## ------------------------------------------------------------------------------
  ## Secure Routes
  ## ------------------------------------------------------------------------------
  namespace :secure do
    resources :projects do
      resources :tasks do
        collection do 
          post :store_attachments
        end
        member do
          get :subtask
        end
        resources :task_attachments, only: [:destroy] do
          get :download
        end

        resources :assigns, only: [:new, :create]
        resources :watchers, only: [:create, :new]
      end
      member do
        get :reports
        resources :agile_boards, only: [:index] do
          collection do
            post :add_task
          end
        end
      end
      resources :comments, except: [:index, :show]
    end    
  end

  ## ------------------------------------------------------------------------------
  ## HR department
  ## ------------------------------------------------------------------------------
  
  resources :holidays do
    collection do
      get :getExistHoliday
      get :import
      get :calendar
      post :import_holiday
    end
  end

  resources :employees do
    collection do
      put :employee_document_update
    end
    resources :employee_documents, only: [:destroy] do
      get :download
    end
  end

  resources :letters do
    member do
      get :generate_pdf
      patch :download_pdf
      get :pdf_viewer      
    end
    collection do
      post :user_info
    end
  end

  ## ------------------------------------------------------------------------------
  ## Admin Routes
  ## ------------------------------------------------------------------------------

  namespace :admin do
    resources :organizations
    
    resources :plans do
      collection do
        get 'getPlan'
      end
    end

    resources :transactions, only: [:index, :show]
  end

  ## Non Authenticate Routes for authorize silent post
  post '/transactions/authorize_silent_post' => 'transactions#authorize_silent_post'
  get '/thank-you' => 'welcome#thank_you', as: :thank_you
end

app/views/layouts/dashboard/_admin_header.html.erb
<nav class='navbar-default navbar-static-side' role='navigation'>
  <div class='sidebar-collapse'>
    <ul class='nav metismenu' id='side-menu'>
      <li class='nav-header'>
        <div class='dropdown profile-element'>
          <span>
            <%= image_tag(current_user_profile.profile_image('small'), class: 'img-circle') %>
          </span>
          <a data-toggle='dropdown' class='dropdown-toggle' href='#'>
            <span class='clear'>
              <span class='block m-t-xs'>
                <strong class='font-bold'><%= current_user.fullname %></strong>
              </span>
              <span class='text-muted text-xs block'>
                <%= my_current_role(@current_role) %>
                <b class='caret'></b>
              </span>
            </span>
          </a>
          <ul class='dropdown-menu animated fadeInRight m-t-xs'>
            <li><%= link_to 'Profile', edit_user_registration_path, data: {disable_with: 'Loading...' } %></li>
            <li><a href='contacts.html'>Contacts</a></li>
            <li><a href='mailbox.html'>Mailbox</a></li>
            <li class='divider'></li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete, data: {disable_with: "<i class='fa fa-spin fa-spinner'></i> wait...".html_safe, confirm: 'Are you sure want to logout?'} do %>
                <i class='fa fa-sign-out'></i> Logout
              <% end %>
            </li>
          </ul>
        </div>
        <div class='logo-element'>PMS</div>
      </li>
      <li class="<%= 'active' if controller.controller_name == 'admin' %>">
      	<%= link_to root_path, data: {disable_with: "<i class='fa fa-spinner fa-spin'></i><span class='nav-label'>Loading...</span>".html_safe } do %>
          <i class='fa fa-th-large'></i>
          <span class='nav-label'>Dashboards</span>
      	<% end %>
      </li>
      <li class="<%= 'active' if controller.controller_name == 'organizations' %>">
      	<%= link_to admin_organizations_path, data: {disable_with: "<i class='fa fa-spinner fa-spin'></i><span class='nav-label'>Loading...</span>".html_safe } do %>
          <i class='fa fa-bank'></i>
          <span class='nav-label'>Organizations</span>
      	<% end %>
      </li>
      
      <li class="<%= 'active' if controller.controller_name == 'plans' %>">
        <%= link_to admin_plans_path, data: {disable_with: loader } do %>
          <i class='fa fa-money'></i>
          <span class='nav-label'>Plans</span>
        <% end %>
      </li>
      
      <li class="<%= 'active' if controller.controller_name == 'transactions' %>">
        <%= link_to admin_transactions_path, data: {disable_with: loader } do %>
          <i class='fa fa-credit-card'></i>
          <span class='nav-label'>Transactions</span>
        <% end %>
      </li>            
    </ul>
  </div>
</nav>

app/views/layouts/dashboard/_footer.html.erb
<div class="footer fixed">
  <div class="pull-right">
    10GB of <strong>250GB</strong> Free.
  </div>
  <div>
    <strong>Copyright</strong> Project Management System &copy; 2016-2017
  </div>
</div>

app/views/layouts/dashboard/_header.html.erb
<nav class='navbar-default navbar-static-side' role='navigation'>
  <div class='sidebar-collapse'>
    <ul class='nav metismenu' id='side-menu'>
      <li class='nav-header'>
        <div class='dropdown profile-element'>          
          <span>            
            <%= image_tag(current_user_profile.profile_image('small'), class: 'img-circle', alt: 'Profile') %>
          </span>
          <a data-toggle='dropdown' class='dropdown-toggle' href='#'>
            <span class='clear'>
              <span class='block m-t-xs'>
                <strong class='font-bold'><%= current_user.fullname %></strong>
              </span>
              <span class='text-muted text-xs block'>
                <%= my_current_role(@current_role) %>
                <b class='caret'></b>
              </span>
            </span>
          </a>
          <ul class='dropdown-menu animated fadeInRight m-t-xs'>
            <li><%= link_to 'Profile', edit_user_registration_path, data: {disable_with: 'Loading...' } %></li>
            <li><a href='contacts.html'>Contacts</a></li>
            <li><a href='mailbox.html'>Mailbox</a></li>
            <li class='divider'></li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete, data: {disable_with: "<i class='fa fa-spin fa-spinner'></i> wait...".html_safe, confirm: 'Are you sure want to logout?'} do %>
                <i class='fa fa-sign-out'></i> Logout
              <% end %>
            </li>
          </ul>
        </div>
        <div class='logo-element'>PMS</div>
      </li>
      <li class="<%= 'active' if controller.controller_name == 'users' && controller.action_name == 'dashboard' %>">
        <%= link_to root_path, data: {disable_with: "<i class='fa fa-spinner fa-spin'></i><span class='nav-label'>Loading...</span>".html_safe } do %>
          <i class='fa fa-th-large'></i>
          <span class='nav-label'>Dashboard</span>
        <% end %>
      </li>

      <% if ['organization_owner'].include?(@current_role) %>
        <li class="<%= 'active' if controller.controller_name == 'users' && controller.action_name != 'dashboard' %>">
          <%= link_to users_path, data: {disable_with: "<i class='fa fa-spinner fa-spin'></i><span class='nav-label'>Loading...</span>".html_safe } do %>
            <i class='fa fa-users'></i>
            <span class='nav-label'>Users</span>
          <% end %>
        </li>
      <% end %>

      <% if ['organization_owner'].include?(@current_role) %>
        <li class="<%= 'active' if controller.controller_name == 'projects' %>">
          <%= link_to projects_path, data: {disable_with: "<i class='fa fa-spinner fa-spin'></i><span class='nav-label'>Loading...</span>".html_safe } do %>
            <i class='fa fa-database'></i>
            <span class='nav-label'>Projects</span>
          <% end %>
        </li>
      <% end %>

      <% if ['organization_owner'].include?(@current_role) %>

        <li class="<%= 'active' if ['holidays', 'employees'].include?(controller.controller_name) %>">
          <a href="javascript:void(0);">
            <i class="fa fa-cogs"></i>
            <span class="nav-label">HR</span>
            <span class="fa arrow"></span>
          </a>
          <ul class="nav nav-second-level collapse" style="height: 0px;">
            <li class="<%= 'active' if controller.controller_name == 'holidays' %>">
              <%= link_to 'Holiday', holidays_path, data: {disable_with: loader} %>
            </li>
            <li class="<%= 'active' if controller.controller_name == 'employees' %>">
              <%= link_to 'Employee', employees_path, data: {disable_with: loader } %>
            </li>
            <li><a href="javascript:void(0);">Leaves</a></li>
            <li><a href="javascript:void(0);">Salary Report</a></li>
          </ul>
        </li>

        <li class="">
          <a href="javascript:void(0);">
            <i class="fa fa-cogs"></i>
            <span class="nav-label">Sales</span>
            <span class="fa arrow"></span>
          </a>
          <ul class="nav nav-second-level collapse" style="height: 0px;">
            <li><a href="javascript:void(0);">Leads</a></li>
          </ul>
        </li>

        <li class="">
          <a href="javascript:void(0);">
            <i class="fa fa-cogs"></i>
            <span class="nav-label">Finance</span>
            <span class="fa arrow"></span>
          </a>
          <ul class="nav nav-second-level collapse" style="height: 0px;">
            <li><a href="javascript:void(0);">Leads</a></li>
          </ul>
        </li>        
      <% end %>

    </ul>

  </div>
</nav>

app/views/layouts/dashboard/_menu.html.erb
<nav class="navbar navbar-fixed-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="javascript:void(0);">
      <i class="fa fa-bars"></i>
    </a>
  </div>
  <ul class="nav navbar-top-links navbar-right">
    <li>
      <span class="m-r-sm text-muted welcome-message">Welcome to Project Management System.</span>
    </li>
    
    <li class="dropdown">
      <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
        <i class="fa fa-envelope"></i>
        <span class="label label-warning">16</span>
      </a>
      
      <ul class="dropdown-menu dropdown-messages">
        <li>
          <div class="dropdown-messages-box">
            <a href="profile.html" class="pull-left">
              <img alt="image" class="img-circle" src="/assets/a7.jpg">
            </a>
            <div>
              <small class="pull-right">46h ago</small>
              <strong>Mike Loreipsum</strong>started following <strong>Monica Smith</strong>. <br>
              <small class="text-muted">3 days ago at 7:58 pm - 10.06.2014</small>
            </div>
          </div>
        </li>
        
        <li class="divider"></li>
        
        <li>
          <div class="dropdown-messages-box">
            <a href="profile.html" class="pull-left">
              <img alt="image" class="img-circle" src="/assets/a4.jpg">
            </a>
            <div>
              <small class="pull-right text-navy">5h ago</small>
              <strong>Chris Johnatan Overtunk</strong> started following <strong>Monica Smith</strong>. <br>
              <small class="text-muted">Yesterday 1:21 pm - 11.06.2014</small>
            </div>
          </div>
        </li>
        
        <li class="divider"></li>
        
        <li>
          <div class="dropdown-messages-box">
            <a href="profile.html" class="pull-left">
              <img alt="image" class="img-circle" src="/assets/profile.jpg">
            </a>
            <div>
              <small class="pull-right">23h ago</small>
              <strong>Monica Smith</strong> love <strong>Kim Smith</strong>. <br>
              <small class="text-muted">2 days ago at 2:30 am - 11.06.2014</small>
            </div>
          </div>
        </li>

        <li class="divider"></li>
                      
        <li>
          <div class="text-center link-block">
            <a href="mailbox.html">
              <i class="fa fa-envelope"></i> <strong>Read All Messages</strong>
            </a>
          </div>
        </li>
        
      </ul>
    </li>
    
    <li class="dropdown">
      <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
        <i class="fa fa-bell"></i>  <span class="label label-primary">8</span>
      </a>
      <ul class="dropdown-menu dropdown-alerts">
        <li>
          <a href="mailbox.html">
            <div>
              <i class="fa fa-envelope fa-fw"></i> You have 16 messages
              <span class="pull-right text-muted small">4 minutes ago</span>
            </div>
          </a>
        </li>

        <li class="divider"></li>
        
        <li>
          <a href="profile.html">
            <div>
              <i class="fa fa-twitter fa-fw"></i> 3 New Followers
              <span class="pull-right text-muted small">12 minutes ago</span>
            </div>
          </a>
        </li>
        
        <li class="divider"></li>
        
        <li>
          <a href="grid_options.html">
            <div>
              <i class="fa fa-upload fa-fw"></i> Server Rebooted
              <span class="pull-right text-muted small">4 minutes ago</span>
            </div>
          </a>
        </li>

        <li class="divider"></li>
        
        <li>
          <div class="text-center link-block">
            <a href="notifications.html">
              <strong>See All Alerts</strong>
              <i class="fa fa-angle-right"></i>
            </a>
          </div>
        </li>
        
      </ul>
    </li>
    
    <li>
      <%= link_to destroy_user_session_path, method: :delete, data: {disable_with: "<i class='fa fa-spin fa-spinner'></i> wait...".html_safe, confirm: 'Are you sure want to logout?'} do %>
        <i class='fa fa-sign-out'></i> Logout
      <% end %>
    </li>
    
    <li>
      <a class="right-sidebar-toggle">
        <i class="fa fa-tasks"></i>
      </a>
    </li>
    
  </ul>
</nav>

app/views/layouts/dashboard/_right-sidebar.html.erb
<div id='right-sidebar'>
  <div class='sidebar-container'>
    <ul class='nav nav-tabs navs-3'>
      <li class='active'><a data-toggle='tab' href='#tab-1'>Notes</a></li>
      <li><a data-toggle='tab' href='#tab-2'>Projects</a></li>
      <li class=''><a data-toggle='tab' href='#tab-3'><i class='fa fa-gear'></i></a></li>
    </ul>
    
    <div class='tab-content'>
      <div id='tab-1' class='tab-pane active'>
        
        <div class='sidebar-title'>
          <h3> <i class='fa fa-comments-o'></i> Latest Notes</h3>
          <small><i class='fa fa-tim'></i> You have 10 new message.</small>
        </div>
    
        <div>
          <div class='sidebar-message'>
            <a href='#'>
              <div class='pull-left text-center'>
                <img alt='image' class='img-circle message-avatar' src='/assets/a1.jpg'>
                <div class='m-t-xs'>
                  <i class='fa fa-star text-warning'></i>
                  <i class='fa fa-star text-warning'></i>
                </div>
              </div>
              <div class='media-body'>
                There are many variations of passages of Lorem Ipsum available. <br>
                <small class='text-muted'>Today 4:21 pm</small>
              </div>
            </a>
          </div>
        </div>

      </div>
      <div id='tab-2' class='tab-pane'>
        <div class='sidebar-title'>
          <h3> <i class='fa fa-cube'></i> Latest projects</h3>
          <small><i class='fa fa-tim'></i> You have 14 projects. 10 not completed.</small>
        </div>
        <ul class='sidebar-list'>
          <li>
            <a href='#'>
              <div class='small pull-right m-t-xs'>9 hours ago</div>
              <h4>Business valuation</h4>
              It is a long established fact that a reader will be distracted.
              <div class='small'>Completion with: 22%</div>
              
              <div class='progress progress-mini'>
                <div style='width: 22%;' class='progress-bar progress-bar-warning'></div>
              </div>
              <div class='small text-muted m-t-xs'>Project end: 4:00 pm - 12.06.2014</div>
            </a>
          </li>
        </ul>
      </div>

      <div id='tab-3' class='tab-pane'>
        <div class='sidebar-title'>
          <h3><i class='fa fa-gears'></i> Settings</h3>
          <small><i class='fa fa-tim'></i> You have 14 projects. 10 not completed.</small>
        </div>
        
        <div class='sidebar-content'>
          <h4>Settings</h4>
          <div class='small'>
            I belive that. Lorem Ipsum is simply dummy text of the printing and typesetting industry.
            And typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.
            Over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
          </div>
        </div>
      </div>

    </div>
  </div>
</div>