config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  ## Root Path
  root to: 'welcome#index'

  ## Devise Authentication 
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks'
  }

  ## ------------------------------------------------------------------------------
  ## Organizations
  ## ------------------------------------------------------------------------------

  resources :organizations do
  	collection do
  		get :getOrganization
  	end
  end

  ## ------------------------------------------------------------------------------
  ## User Routes
  ## ------------------------------------------------------------------------------

  resources :users do
    collection do
      ## Non Authentication Routes
      get :getUser
      get :existUser
      get :lockUser
      get :profile
      get :getPassword
      get :creditCardValidation
      get :lock_screen
    end
  end

  resources :invitations do
    collection do
      get :existMember
      get :accept
      get :thank_you
      post :accept_invitation
    end
  end

  resources :projects do
    collection do
      get :getProNameUniq ## Get Uniq Project Name
    end
    member do
      post :invitation
    end
    resources :clients, except: [:index]
  end

  ## Dashboard Routes
  get '/dashboard' => 'users#dashboard', as: :user_dashboard
  get '/admin/dashboard' => 'admin#dashboard', as: :admin_dashboard

  ## ------------------------------------------------------------------------------
  ## Secure Routes
  ## ------------------------------------------------------------------------------
  namespace :secure do
    resources :projects do
      resources :tasks do
        collection do 
          post :store_attachments
        end
        member do
          get :subtask
        end
        resources :task_attachments, only: [:destroy] do
          get :download
        end

        resources :assigns, only: [:new, :create]
        resources :watchers, only: [:create, :new]
      end
      member do
        get :reports
        resources :agile_boards, only: [:index] do
          collection do
            post :add_task
          end
        end
      end
      resources :comments, except: [:index, :show]
    end    
  end

  ## ------------------------------------------------------------------------------
  ## HR department
  ## ------------------------------------------------------------------------------
  
  resources :holidays do
    collection do
      get :getExistHoliday
      get :import
      get :calendar
      post :import_holiday
    end
  end

  resources :employees do
    collection do
      put :employee_document_update
    end
    resources :employee_documents, only: [:destroy] do
      get :download
    end
  end

  resources :letters do
    member do
      get :generate_pdf
      patch :download_pdf
      get :pdf_viewer      
    end
    collection do
      post :user_info
    end
  end

  ## ------------------------------------------------------------------------------
  ## Admin Routes
  ## ------------------------------------------------------------------------------

  namespace :admin do
    resources :organizations
    
    resources :plans do
      collection do
        get 'getPlan'
      end
    end

    resources :transactions, only: [:index, :show]
  end

  ## Non Authenticate Routes for authorize silent post
  post '/transactions/authorize_silent_post' => 'transactions#authorize_silent_post'
  get '/thank-you' => 'welcome#thank_you', as: :thank_you
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id              :integer          not null, primary key
#  name            :string
#  description     :text
#  start_date      :date
#  end_date        :date
#  total_hour      :float            default(0.0)
#  url             :text
#  status_id       :integer          default(1)
#  organization_id :integer
#  slug            :string
#  key             :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  keywords        :text
#

class Project < ApplicationRecord
	## Friendly ID
	extend FriendlyId
  friendly_id :name, use: :slugged
	
	## Callbacks
	before_create :generate_short_uniq_key

	## Relationship
	belongs_to :organization

  has_many :projects_users
  has_many :users, through: :projects_users
  
  has_many :clients, -> {order 'created_at ASC'}
  accepts_nested_attributes_for :clients, allow_destroy: true

  has_many :task_attachments
  accepts_nested_attributes_for :task_attachments, allow_destroy: true

  has_many :tasks, -> {order 'created_at DESC'}
  accepts_nested_attributes_for :tasks, allow_destroy: true
  
  has_many :comments, -> {order 'created_at DESC'}

  ## Validations
  validates :name, :description, presence: true
  validates :name, uniqueness: {scope: :organization}

  serialize :keywords, Array

	## Callback methods
	def generate_short_uniq_key
		result 		= name.split.map(&:first).join
		self.key 	= result.length < 3 ? name[0..2].upcase : result.upcase
	end

	## Method
	def status
		Rails.application.secrets.project_statuses[status_id]
	end

  def self.search(srch=nil)
    if srch.present?
      #where('email LIKE ? or firstname LIKE ? or lastname LIKE ?', "%#{srch}%", "%#{srch}%", "%#{srch}%").order('created_at DESC')
    else
      order('created_at DESC')
    end
  end

  def last_updated
  	updated_at.strftime('%d/%m/%Y')
  end

  def created_date
  	created_at.strftime('%d/%m/%Y')
  end

  def to_start_date
    start_date? ? start_date.strftime('%d %b, %Y') : ''
  end

  def to_end_date
    end_date? ? end_date.strftime('%d %b, %Y') : 'Not Define'
  end
end

app/controllers/projects_controller.rb
class ProjectsController < BaseController

  expose :projects, ->{ current_organization.projects.search(params[:search]) }
  expose(:project, find_by: :slug)

  add_breadcrumb 'Home', :user_dashboard_path
  add_breadcrumb 'Projects', :projects_path

  def new
  	respond_to do |format|
  		format.html{redirect_to projects_path}
  		format.js
  	end
  end

  def create
    project = current_organization.projects.build(project_params)
    project.save if project.valid?
    respond_to do |format|
      format.html{redirect_to projects_path, notice: 'Successfully created projects'}
      format.js
    end    
  end

  def edit
    add_breadcrumb 'Edit'
    gon.project_id = project.id
  end

  def update
    if project.update(update_project_params)
      redirect_to projects_path, notice: 'Successfully updated project !'
    else
      render action: :edit
    end
  end

  def invitation
    if project.user_ids.include?(params[:project][:user_ids].to_i)
      msg = 'User already invited'
    else      
      project.user_ids =  project.user_ids << params[:project][:user_ids].to_i
      msg = 'Successfully send invitation to user !'
    end
    respond_to do |format|
      format.html{redirect_to project, notice: msg}
      format.js
    end
  end

  def getProNameUniq
    if params[:project_id].present?
      project = Project.where('lower(name) = ? AND organization_id = ? AND id != ?', params[:project][:name].downcase, current_organization.id, params[:project_id]).try(:last)
    else
      project = Project.where('lower(name) = ? AND organization_id = ?', params[:project][:name].downcase, current_organization.id).try(:last)
    end
    render json: project.present? ? false : true
  end

  private

  def project_params
    params.require(:project).permit(:name, :description)
  end

  def update_project_params
    params.require(:project).permit(:name, :description, :start_date, :end_date, :status_id, :url, :user_ids, keywords: [], 
      clients_attributes: [:id, :fullname, :company_name, :email, :email2, :phone_number, :mobile_number, :skype, :address, :user_id, '_destroy', :project_id]
    )
  end

end

app/controllers/secure/projects_controller.rb
class Secure::ProjectsController < MainController

  expose :projects, ->{ current_user.projects.search(params[:search]) }
  expose(:project, find_by: :slug)
  expose :tasks, fetch: ->{ get_project_tasks }

  add_breadcrumb 'Home', :user_dashboard_path
  add_breadcrumb 'Projects', :secure_projects_path

 	def show
 		if params[:task].present?
 			task = project.tasks.where("status_id = ?", params[:status]).order('created_at ASC').try(:first)
 			if task.present?
 				redirect_to secure_project_task_path(project, task, status: params[:status])
			else
				redirect_to secure_project_path(project, status: params[:status])
			end 				
 		end
 	end

  def reports
    add_breadcrumb project.name, secure_project_path(project)
    add_breadcrumb 'Chart'
    @pieChartReportForProject = []
    @report2 = []
    if project.tasks.present?
      if params[:start_date].present? && params[:end_date].present?
        proj_tasks = project.tasks.where('DATE(created_at) >= ? AND DATE(created_at) <= ?', params[:start_date].to_date, params[:end_date].to_date).select('id, status_id, issue_type_id')
      else
        proj_tasks = project.tasks.select('id, status_id, issue_type_id')
      end
      report1 = proj_tasks.group_by{|t| t.status}
      report2 = proj_tasks.group_by{|t| t.issue_type}
      if report1.present?
        report1.each do |status, ptasks|
          @pieChartReportForProject << {label: status, data: ptasks.flatten.count, color:  ptasks.first.status_color}
        end
      end

      if report2.present?
        report2.each do |itype, ptasks|
          @report2 << {label: itype, data: ptasks.flatten.count, color:  ptasks.first.issue_type_color}
        end
      end
    end    
    gon.pieChartReportForProject = @pieChartReportForProject
    gon.report2 = @report2
  end

  private

  def get_project_tasks  	
  	project.tasks.only_parents.search(params)
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
	def project_created_at(created_at)
		html = ''
		html += "<small>Created #{created_at.strftime('%d.%m.%Y') }</small>"
		html.html_safe
	end

	def project_status(project)
		html = ''
		case project.status_id
		when 1
			html += "<span class='label label-plain'>#{project.status}</span>"
		when 2
			html += "<span class='label label-primary'>#{project.status}</span>"
		when 3
			html += "<span class='label label-success'>#{project.status}</span>"
		when 4
			html += "<span class='label label-warning'>#{project.status}</span>"
		when 5
			html += "<span class='label label-danger'>#{project.status}</span>"
		end
		html.html_safe
	end
end

app/helpers/secure/projects_helper.rb
module Secure::ProjectsHelper
	def task_code(status_id, code)
		case status_id
		when 1
			html = "<span class='label label-danger'>#{code}</span>"
		when 2
			html = "<span class='label label-danger2'>#{code}</span>"
		when 3
			html = "<span class='label label-warning'>#{code}</span>"
		when 4
			html = "<span class='label label-primary'>#{code}</span>"
		when 5		
			html = "<span class='label label-plain'>#{code}</span>"
		end
		html.html_safe
	end	
end

app/views/projects/_client-list.html.erb
<% project.clients.each do |client| %>		
	<div id='<%= client.uniq_number %>' class='col-lg-6'>
		<div class='contact-box client-view'>
			<%= render partial: '/clients/view', locals: {client: client} %>
		</div>
	</div>
<% end %>

app/views/projects/_client_info.html.erb
<div class='col-lg-12'>
	<%= link_to "<i class='fa fa-plus'></i> Add Client".html_safe, new_project_client_path(project), data: {disable_with: loader}, remote: true %>
</div>
<hr>
<% if project.clients.present? %>
	<div class="clients">
		<%= render partial: '/projects/client-list' %>
	</div>
<% else %>
	<p> No Client For Current Project ! </p>
<% end %>

app/views/projects/_new.html.erb
<div class='modal inmodal' id='new_project_popup' tabindex='-1' role='dialog' aria-hidden='true'>
  <div class='modal-dialog'>
    <div class='modal-content animated bounceInRight'>
      <div class='modal-header'>
        <button type='button' class='close' data-dismiss='modal'><span aria-hidden='true'>&times;</span><span class='sr-only'>Close</span></button>
        <h4 class='modal-title'>Add New Project</h4>
        <small class="font-bold">
          you can plan, track and report on all of your work within a project. <br/>
          You can also track all the work activity as transitions through a streamlined process.
        </small>
      </div>
      <%= form_for project, html: {class: 'form-horizontal new-project'} do |form| %>
        <div class='modal-body'>

          <div class="form-group">
            <%= form.label :name, 'Project Name', class: 'col-sm-3 control-label' %>
            <div class="col-sm-9">
              <%= form.text_field :name, placeholder: 'Project Name', class: 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <%= form.label :description, 'Description', class: 'col-sm-3 control-label' %>
            <div class="col-sm-9">
              <%= form.text_area :description, placeholder: 'Project Description', class: 'form-control', rows: 4 %>
            </div>
          </div>
          
          <span class='help-block m-b-none text-center'>
            <b>Note :</b> You can add more detail for project on the edit page.
          </span>
        </div>
        <div class='modal-footer'>
          <button type='button' class='btn btn-white' data-dismiss='modal'>Close</button>                    
          <button type='submit' class='btn btn-primary m-b' data-disable-with="<i class='fa fa-spin fa-spinner'></i> Please Wait...">
            Save
          </button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/_project_details.html.erb
<%= form_for project, html: {class: 'form-horizontal edit-project-detail'} do |form| %>

  <div class='form-group'>
    <%= form.label :name, class: 'col-sm-2 control-label' %>
    <div class='col-sm-10'>        
      <%= form.text_field :name, placeholder: 'Write your project name here ... ', class: 'form-control' %>
    </div>
  </div>

  <div class='form-group'>
    <%= form.label :description, class: 'col-sm-2 control-label' %>
    <div class='col-sm-10'>
      <%= form.text_area :description, class: 'summernote' %>
    </div>
  </div>

  <div class='form-group'>
    <%= form.label :keywords, class: 'col-sm-2 control-label' %>
    <div class='col-sm-10'>
      <%= form.select :keywords, options_for_select(Rails.application.secrets.keywords, form.object.keywords), {}, {class: 'chosen-select', multiple: true} %>
    </div>
  </div>

  <div class='form-group'>
    <%= form.label :url, 'URL', class: 'col-sm-2 control-label' %>
    <div class='col-sm-10'>        
      <%= form.url_field :url, placeholder: 'Project Live/Staging URL', class: 'form-control' %>
    </div>
  </div>

  <div class='form-group'>
    <%= form.label :start_date, 'Start Date', class: 'col-sm-2 control-label' %>
    <div class='col-sm-3'>
      <div class="input-group date">
        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>              
        <%= form.text_field :start_date, value: form.object.start_date.present? ? form.object.start_date.strftime('%d/%m/%Y') : '', class: 'form-control', placeholder: 'DD/MM/YYYY' %>
      </div>
    </div>

    <%= form.label :end_date, 'End Date', class: 'col-sm-2 control-label' %>
    <div class='col-sm-3'>
      <div class="input-group date">
        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>              
        <%= form.text_field :end_date, value: form.object.end_date.present? ? form.object.end_date.strftime('%d/%m/%Y') : '', class: 'form-control', placeholder: 'DD/MM/YYYY' %>
      </div>
    </div>
  </div>

  <div class='form-group'>
    <%= form.label :status_id, 'Status', class: 'col-sm-2 control-label' %>
    <div class='col-sm-3'>
      <%= form.select :status_id, options_for_select(Rails.application.secrets.project_statuses.invert.to_a, form.object.status_id ), {include_blank: false }, {class: 'form-control'} %>
    </div>
  </div>

  <div class="clearfix"></div>
  <div class='hr-line-dashed'></div>
    
  <div class='form-group'>
    <div class='col-sm-8 col-sm-offset-2'>
      <%= button_tag 'Update', class: 'btn btn-primary', data: { disable_with: loader} %>
    </div>
  </div>

<% end %>

app/views/projects/edit.html.erb
<% content_for :title, "Edit Project" %>
<div class='row wrapper border-bottom white-bg page-heading'>
  <div class='col-sm-6'>
    <%= show_breadcrumb("Edit Project - #{project.name} - (#{project.key})") %>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight ecommerce">
  <div class="row">
    <div class="col-lg-12">
      <div class="tabs-container">
        <ul class="nav nav-tabs">
          <li class="active">
          	<a data-toggle="tab" href="#project-detail-tab-1"> Project Detail</a>
          </li>
          <li class="">
          	<a data-toggle="tab" href="#client-info-tab-2"> Client Information </a>
          </li>
          <li class="">
          	<a data-toggle="tab" href="#finance-detail-tab-3"> Finance Detail </a>
          </li>
          <li class="">
          	<a data-toggle="tab" href="#document-tab-4"> Documents</a>
          </li>
        </ul>
        <div class="tab-content">
         	<div id="project-detail-tab-1" class="tab-pane active">
            <div class="panel-body">
            	<%= render partial: '/projects/project_details' %>       
            </div>
          </div>
          
          <div id="client-info-tab-2" class="tab-pane">
            <div class="panel-body">
            	<%= render partial: '/projects/client_info' %>
            </div>
          </div>
          
          <div id="finance-detail-tab-3" class="tab-pane">
          	<div class="panel-body">
							<div class="table-responsive">
								<%= render partial: '/projects/finance_detail' %>
            	</div>
            </div>
          </div>
          
          <div id="document-tab-4" class="tab-pane">
            <div class="panel-body">
            	<%= render partial: '/projects/documents' %>
           </div>
          </div>

          <div class='project-pop-dply'></div>
        </div>
      </div>
    </div>
  </div>
</div>

                            

app/views/projects/index.html.erb
<% content_for :title, "Projects" %>
<div class='row wrapper border-bottom white-bg page-heading'>
  <div class='col-sm-6'>
    <%= show_breadcrumb('Projects') %>
  </div>
</div>

<div class='row'>
	<div class='col-lg-12'>
  	<div class='wrapper wrapper-content animated fadeInUp'>
      <div class='ibox'>
        <div class='ibox-title'>
          <h5>All projects associated to this organization</h5>
          <div class='new-project-popup'></div>
          <div class='ibox-tools'>          	
          	<%= link_to new_project_path, class: 'btn btn-primary btn-xs', data: {disable_with: loader}, remote: true do %>
          		Create New Project</i>
          	<% end %>            
          </div>
        </div>        
        <div class='ibox-content'>
          <% if projects.present? %>
            <div class='row m-b-sm m-t-sm'>
              <div class='col-md-1'>
                <button type='button' id='loading-example-btn' class='btn btn-white btn-sm' ><i class='fa fa-refresh'></i> Refresh</button>
              </div>
              <div class='col-md-11'>
                <div class='input-group'>
                	<input type='text' placeholder='Search' class='input-sm form-control'>
                	<span class='input-group-btn'>
                  	<button type='button' class='btn btn-sm btn-primary'> <i class='fa fa-search'></i> Search</button>
                  </span>
                </div>
              </div>
            </div>
            <div class='project-list'>
              <table class='table table-hover'>
                <tbody>
                  <% projects.each do |project| %>
                    <tr>
                      <td class='project-status'><%= project_status(project) %></td>
                    	<td class='project-title'>                        
                        <%= link_to project.name, project %><br/>
                        <%= project_created_at(project.created_at) %>
                      </td>
                      <td class='project-completion'>
                        <small>Completion with: 0%</small>
                        <div class='progress progress-mini'>
                          <div style='width: 0%;' class='progress-bar'></div>
                        </div>
                      </td>
                      <% if project.users.present? %>
                        <td class='project-people'>
                          <% project.users.limit(5).each do |user| %>
                            <%= link_to 'javascript:void(0);' do %>
                              <%= image_tag(user.profile_image('small'), class: 'img-circle', title: user.fullname) %>
                            <% end %>
                          <% end %>
                        </td>
                      <% end %>
                      <td class='project-actions'>
                        <%= link_to project, class: 'btn btn-white btn-sm', data: {disable_with: loader} do %>
                          <i class='fa fa-folder'></i> View
                        <% end %>
                        <%= link_to edit_project_path(project), class: 'btn btn-white btn-sm', data: {disable_with: loader} do %>
                          <i class='fa fa-pencil'></i> Edit
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
               	</tbody>
              </table>
            </div>
          <% else %>
            <p> No Projects Found !</p>
          <% end %>            
        </div>
      </div>
    </div>
 	</div>
</div>

app/views/projects/new.js.erb
$('.new-project-popup').html("<%= escape_javascript(render partial: '/projects/new') %>")
$('#new_project_popup').modal({backdrop: 'static', keyboard: false});


$('.new-project').validate({
	rules: {
		'project[name]': {
			required: true,
			remote: {
				type: 'get',
				url: '/projects/getProNameUniq',
				dataType: 'json'
			}
		},
		'project[description]': {
			required: true
		}
	},
	messages: {
		'project[name]': {
			required: "Project name can't be blank !",
			remote: 'Already exist please you another !'
		},
		'project[description]': {
			required: "Description can't be blank !"
		}		
	}

})

app/views/projects/show.html.erb
<% content_for :title, "View Project" %>
<div class='row wrapper border-bottom white-bg page-heading'>
  <div class='col-sm-6'>
    <%= show_breadcrumb("Project - #{project.name}") %>
  </div>
</div>

<div class='row'>
	<div class='col-lg-9'>
		<div class='wrapper wrapper-content animated fadeInUp'>
			<div class='ibox'>
				<div class='ibox-content'>
					<div class='row'>
						<div class='col-lg-12'>
							<div class='m-b-md'>
								<%= link_to edit_project_path(project), class: 'btn btn-white btn-xs pull-right', data: {disable_with: loader} do %>
                  <i class='fa fa-pencil'></i> Edit Project
                <% end %>								
								<h2><%= project.name %></h2>
							</div>
							
							<dl class='dl-horizontal'>
								<dt>Status:</dt> 
								<dd><%= project_status(project) %></dd>								
							</dl>
						</div>
						<% if project.description.present? %>
							<div class='col-lg-12'>
								<dl class='dl-horizontal'>
									<dt>Description:</dt>
									<dd><%= project.description.html_safe %></dd>
								</dl>
							</div>
						<% end %>
					</div>
					<div class='row'>
						<div class='col-lg-5'>
							<dl class='dl-horizontal'>
								<dt>Created by:</dt> <dd><%= project.organization.name %></dd>
								<dt>Messages:</dt> <dd>  000</dd>
								<% if project.clients.present? %>
									<dt>Client:</dt> 
									<% project.clients.each do |client| %>
										<dd><%= link_to client.fullname, 'javascript:void(0);', class: 'text-navy' %></dd>
									<% end %>									
								<% end %>
								<dt>Version:</dt> <dd> 	v1.4.2 </dd>
							</dl>
						</div>
						<div class='col-lg-7' id='cluster_info'>
							<dl class='dl-horizontal'>
								<dt>Last Updated:</dt> <dd><%= project.last_updated %></dd>
								<dt>Created:</dt> <dd> <%= project.created_date %> </dd>
								<% if project.user_ids.present? %>
									<dt>Members:</dt>
									<dd class='project-people'>
										<% project.users.each do |user| %>
											<a href='javascript:void(0);'>												
												<%= image_tag(user.profile_image('small'), title: user.fullname, class: 'img-circle') %>
											</a>
										<% end %>
									</dd>
								<% end %>
							</dl>
						</div>
					</div>
					
					<div class='row'>
						<div class='col-lg-12'>
							<dl class='dl-horizontal'>
								<dt>Completed:</dt>
								<dd>
									<div class='progress progress-striped active m-b-sm'>
										<div style='width: 60%;' class='progress-bar'></div>
									</div>
									<small>Project completed in 
										<strong>60%</strong>. 
										Remaining close the project, sign a contract and invoice.
									</small>
								</dd>
							</dl>
						</div>
					</div>

					<div class='row m-t-sm'>
						<div class='col-lg-12'>
							<div class='panel blank-panel'>
								<div class='panel-heading'>
									<div class='panel-options'>
										<ul class='nav nav-tabs'>
											<li class='active'><a href='#project-member-tab-1' data-toggle='tab' aria-expanded='true'>Project Members</a></li>
											<li class=''><a href='#tab-1' data-toggle='tab' aria-expanded='true'>Users messages</a></li>
											<li class=''><a href='#tab-2' data-toggle='tab' aria-expanded='false'>Last activity</a></li>
										</ul>
									</div>
								</div>

								<div class='panel-body padtop0'>
									<div class='tab-content'>

										<div class='tab-pane active' id='project-member-tab-1'>
											<% if project.user_ids.present? %>
												<div class='table-responsive'>
	                        <table class='table table-striped table-hover'>
	                          <tbody>
	                          	<% project.users.each do |user| %>
		                            <tr id='<%= user.slug %>'>
		                              <td class='client-avatar'>
		                              	<%= image_tag(user.profile_image('small')) %>
		                              </td>
		                              <td>
		                              	<a data-toggle='tab' href='javascript:void(0);' class='client-link'><%= user.fullname %></a>
		                              </td>
		                              <td><%= role_for_current_organization(user, @current_organization) %></td>
		                              <td class='contact-type'><i class='fa fa-envelope'></i></td>
		                              <td><%= user.email %></td>
		                            </tr>
	                            <% end %>
	                          </tbody>
	                        </table>
	                      </div>
	                    <% else %>
	                    	<h4>No members found for this project !</h4>
	                    <% end %>
										</div>

										<div class='tab-pane' id='tab-1'>
											<div class='feed-activity-list'>
												<div class='feed-element'>
													<a href='#' class='pull-left'>
														<img alt='image' class='img-circle' src='/assets/a2.jpg'>
													</a>
													<div class='media-body '>
														<small class='pull-right'>2h ago</small>
														<strong>Mark Johnson</strong> posted message on <strong>Monica Smith</strong> site. <br>
														<small class='text-muted'>Today 2:10 pm - 12.06.2014</small>
														<div class='well'>
															Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.
															Over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
														</div>
													</div>
												</div>
												<div class='feed-element'>
													<a href='#' class='pull-left'>
														<img alt='image' class='img-circle' src='/assets/a3.jpg'>
													</a>
													<div class='media-body '>
														<small class='pull-right'>2h ago</small>
														<strong>Janet Rosowski</strong> add 1 photo on <strong>Monica Smith</strong>. <br>
														<small class='text-muted'>2 days ago at 8:30am</small>
													</div>
												</div>
												<div class='feed-element'>
													<a href='#' class='pull-left'>
														<img alt='image' class='img-circle' src='/assets/a4.jpg'>
													</a>
													<div class='media-body '>
														<small class='pull-right text-navy'>5h ago</small>
														<strong>Chris Johnatan Overtunk</strong> started following <strong>Monica Smith</strong>. <br>
														<small class='text-muted'>Yesterday 1:21 pm - 11.06.2014</small>
														<div class='actions'>
															<a class='btn btn-xs btn-white'><i class='fa fa-thumbs-up'></i> Like </a>
															<a class='btn btn-xs btn-white'><i class='fa fa-heart'></i> Love</a>
														</div>
													</div>
												</div>
											</div>
										</div>
										
										<div class='tab-pane' id='tab-2'>
											<table class='table table-striped'>
												<thead>
													<tr>
														<th>Status</th>
														<th>Title</th>
														<th>Start Time</th>
														<th>End Time</th>
														<th>Comments</th>
													</tr>
												</thead>
												<tbody>
													<tr>
														<td>
															<span class='label label-primary'>
																<i class='fa fa-check'></i> Completed
															</span>
														</td>
														<td> Create project in webapp </td>
														<td> 12.07.2014 10:10:1 </td>
														<td> 14.07.2014 10:16:36 </td>
														<td>
															<p class='small'>
																Lorem Ipsum is.
															</p>
														</td>
													</tr>
												</tbody>
											</table>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>

				</div>
			</div>
		</div>
	</div>

	<div class='col-lg-3 pad0'>
		<div class='wrapper wrapper-content project-manager'>
			<div class='ibox-content'>
				<h4>Project Invitation</h4>
				
				<%= form_tag invitation_project_path(project), method: :post, class: 'project-invitation' do |form| %>
          <div class='form-group'>
            <%= select_tag 'project[user_ids]', options_for_select(@current_organization.users.collect{|t| [t.fullname_with_designation(@current_organization), t.id] }), {include_blank: 'Select User', class: 'form-control'} %>
            <span class='help-block m-b-none view-user-info-for-invitation text-center hide'>
            	<p><%= image_tag(current_user.profile_image('small'), class: 'img-circle img-center') %></p>
            	<h4></h4>
            	<h5></h5>
            </span>
          </div>

				  <div class='clearfix'></div>

			    <div class='hr-line-dashed'></div>
			    
			    <div class='form-group'>
			      <div class='text-center'>			      	
			        <%= button_tag 'Send', class: 'btn btn-primary', data: { disable_with: loader} %>
			      </div>
			    </div>

        <% end %>

			</div>
		</div>
	</div>
</div>