config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  ## Root Path
  root to: 'welcome#index'

  ## Devise Authentication 
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks'
  }

  ## ------------------------------------------------------------------------------
  ## Organizations
  ## ------------------------------------------------------------------------------

  resources :organizations do
  	collection do
  		get :getOrganization
  	end
  end

  ## ------------------------------------------------------------------------------
  ## User Routes
  ## ------------------------------------------------------------------------------

  resources :users do
    collection do
      ## Non Authentication Routes
      get :getUser
      get :existUser
      get :lockUser
      get :profile
      get :getPassword
      get :creditCardValidation
      get :lock_screen
    end
  end

  resources :invitations do
    collection do
      get :existMember
      get :accept
      get :thank_you
      post :accept_invitation
    end
  end

  resources :projects do
    collection do
      get :getProNameUniq ## Get Uniq Project Name
    end
    member do
      post :invitation
    end
    resources :clients, except: [:index]
  end

  ## Dashboard Routes
  get '/dashboard' => 'users#dashboard', as: :user_dashboard
  get '/admin/dashboard' => 'admin#dashboard', as: :admin_dashboard

  ## ------------------------------------------------------------------------------
  ## Secure Routes
  ## ------------------------------------------------------------------------------
  namespace :secure do
    resources :projects do
      resources :tasks do
        collection do 
          post :store_attachments
        end
        member do
          get :subtask
        end
        resources :task_attachments, only: [:destroy] do
          get :download
        end

        resources :assigns, only: [:new, :create]
        resources :watchers, only: [:create, :new]
      end
      member do
        get :reports
        resources :agile_boards, only: [:index] do
          collection do
            post :add_task
          end
        end
      end
      resources :comments, except: [:index, :show]
    end    
  end

  ## ------------------------------------------------------------------------------
  ## HR department
  ## ------------------------------------------------------------------------------
  
  resources :holidays do
    collection do
      get :getExistHoliday
      get :import
      get :calendar
      post :import_holiday
    end
  end

  resources :employees do
    collection do
      put :employee_document_update
    end
    resources :employee_documents, only: [:destroy] do
      get :download
    end
  end

  resources :letters do
    member do
      get :generate_pdf
      patch :download_pdf
      get :pdf_viewer      
    end
    collection do
      post :user_info
    end
  end

  ## ------------------------------------------------------------------------------
  ## Admin Routes
  ## ------------------------------------------------------------------------------

  namespace :admin do
    resources :organizations
    
    resources :plans do
      collection do
        get 'getPlan'
      end
    end

    resources :transactions, only: [:index, :show]
  end

  ## Non Authenticate Routes for authorize silent post
  post '/transactions/authorize_silent_post' => 'transactions#authorize_silent_post'
  get '/thank-you' => 'welcome#thank_you', as: :thank_you
end

app/models/letter.rb
# == Schema Information
#
# Table name: letters
#
#  id              :integer          not null, primary key
#  organization_id :integer
#  description     :text
#  title           :string
#  is_default      :boolean          default(FALSE)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Letter < ApplicationRecord
	
	extend FriendlyId
  friendly_id :title, use: :slugged	

	## Relationship
	belongs_to :organization

	## Validations
	validates :description, :title, presence: true

	def should_generate_new_friendly_id?
		title_changed?
	end
end

app/controllers/letters_controller.rb
class LettersController < MainController
	
	expose :letters, ->{ @current_organization.letters }
	expose :letter, find_by: :slug

  add_breadcrumb 'Home', :user_dashboard_path
  add_breadcrumb 'Letters', :letters_path

  include GenerateLetterPdf

  def new
  	add_breadcrumb 'New'
  end

  def create
  	letter = @current_organization.letters.build(letter_params)
  	if letter.save
  		redirect_to letters_path, notice: 'Successfully added letter!'
  	else
  		render action: :new
  	end
  end

  def edit
  	add_breadcrumb 'Edit'
  end

  def update
  	if letter.update(letter_params)
  		redirect_to letter, notice: 'Successfully updated letter !'
  	else
  		render action: :edit
  	end
  end

  def destroy
    letter.destroy if letter.present?
    redirect_to letters_path, notice: 'Successfully deleted letter !'
  end

  def show
  	add_breadcrumb 'View'
  end

  def generate_pdf
    respond_to do |format|
      format.html{redirect_to letters_path}
      format.js
    end    
  end

  def download_pdf
    if params[:letter][:organization_title].present?
      @current_organization.update_column(:title, params[:letter][:organization_title])
    end
    if params[:profile].present?
      employee = @current_organization.organizations_users.find_by(user_id: params[:letter][:employee_id])
      employee.profile.update_column(:designation, params[:profile][:designation])      
    end
    generate_pdf_for_letters(letter, params[:letter], @current_organization)    
  end

  def user_info
    @employee = @current_organization.organizations_users.find_by(user_id: params[:employee_id])
    respond_to do |format|
      format.html{render nothing: true}
      format.js
    end
  end

  private

  def letter_params
  	params.require(:letter).permit(:title, :description, :organization_id)
  end

end

app/helpers/letters_helper.rb
module LettersHelper
end

app/views/letters/_form.html.erb
<%= form_for letter, html: { class: 'add-new-letter' } do |form| %>

  <div class='form-group'>
    <%= form.label :title, class: '' %>
    <%= form.text_field :title, placeholder: 'Title', class: 'form-control' %>	  
	</div>

  <div class='form-group'>
    <%= form.label :description, class: 'control-label' %>
    <%= form.text_area :description, placeholder: 'Description', class: 'form-control summernote-letter' %>
	</div>

  <div class="hr-line-dashed"></div>
  
  <div class="form-group">
    <div class="col-sm-6 col-sm-offset-2">
      <%= link_to 'Cancel', letters_path, data: {disable_with: loader }, class: 'btn btn-white' %>
      <button type='submit' class='btn btn-primary m-b' data-disable-with="<i class='fa fa-spin fa-spinner'></i> Save Changes...">
        <%= form.object.new_record? ? 'Create' : 'Update' %>
      </button>
    </div>
  </div>
  <div class="clearfix"></div>
<% end %>

app/views/letters/_generate_pdf.html.erb
<div class='modal inmodal' id='view-generate-pdf-form-popup' tabindex='-1' role='dialog' aria-hidden='true'>
  <div class='modal-dialog'>
    <div class='modal-content animated bounceInRight'>
      <div class='modal-header'>
        <button type='button' class='close' data-dismiss='modal'><span aria-hidden='true'>&times;</span><span class='sr-only'>Close</span></button>
        <h4 class='modal-title'>          
          Generate PDF for <%= letter.title %>
        </h4>
      </div>
      <%= form_for letter, url: {controller: 'letters', action: 'download_pdf' }, html: { class: 'generate-pdf-letter-validation' } do |form| %>
        <div class='modal-body'>

          <% if !@current_organization.title.present? && letter.description.scan('[COMPANY]').present? %>
            <div class='form-group'>
              <label>Name of Organization</label>
              <%= text_field_tag 'letter[organization_title]', nil, placeholder: 'Name of organization', class: 'form-control' %>
            </div>
          <% end %>

          <div class='form-group'>
            <label>Employee <span class="danger">*</span></label>
            <%= select_tag 'letter[employee_id]', options_for_select(@current_organization.organizations_users.collect{|u| ["#{u.profile.fullname} (#{u.profile.designation})", u.user_id] }), prompt: 'Select Employee', class: 'form-control required' %>
          </div>
          
          <div class='employee-info'></div>

          <% if letter.description.scan('[SUPERVISOR]').present? || letter.description.scan('[SUPERVISOR-POSITION]').present? %>
            <div class='form-group'>
              <label>Supervisor <span class="danger">*</span></label>
              <%= select_tag 'letter[supervisor_id]', options_for_select(@current_organization.organizations_users.collect{|u| ["#{u.profile.fullname} (#{u.profile.designation})", u.user_id] }), prompt: 'Select Supervisor', class: 'form-control required' %>
            </div>
          <% end %>

          <% if letter.description.scan('[SENDER-NAME]').present? %>
            <div class='form-group'>
              <label>Sender Name <span class="danger">*</span></label>
              <%= text_field_tag 'letter[sender_name]', nil, placeholder: 'Sender Name', class: 'form-control required' %>
            </div>
          <% end %>

          <% if letter.description.scan('[SALARY]').present? %>
            <div class='form-group'>
              <label>Salary <span class="danger">*</span></label>
              <%= text_field_tag 'letter[salary]', nil, placeholder: 'Salary', class: 'form-control required' %>
            </div>          
          <% end %>
        </div>

        <div class='modal-footer'>          
          <button type='submit' class='btn btn-primary m-b' data-disable-with="<i class='fa fa-spin fa-spinner'></i> Generating PDF">
            Generate PDF
          </button>          
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/letters/_help.html.erb
<div class="ibox right-panel-letter-box">
	<div class="ibox-content">
		<div class="">
			<% if controller.action_name == 'edit' %>				
				<%= link_to 'Generate PDF', generate_pdf_letter_path(letter), class: 'btn btn-primary btn-rounded', data: {disable_with: loader, remote: true} %>
				<div class="pull-right">
					<%= link_to 'View', letter_path(letter), class: 'btn btn-white btn-sm', data: {disable_with: loader} %>
					<% if !letter.is_default? %>
						<%= link_to 'Delete', letter_path(letter), class: 'btn btn-danger btn-sm', data: {disable_with: loader, confirm: 'Are you sure want to delete this letter? '}, method: :delete %>
					<% end %>
				</div>
				<hr/>
			<% elsif controller.action_name == 'show' %>
				<%= link_to 'Generate PDF', generate_pdf_letter_path(letter), class: 'btn btn-primary btn-rounded', data: {disable_with: loader, remote: true} %>
				<div class="pull-right">
					<%= link_to 'Edit', edit_letter_path(letter), class: 'btn btn-white btn-sm', data: {disable_with: loader} %>
					<% if !letter.is_default? %>
						<%= link_to 'Delete', letter_path(letter), class: 'btn btn-danger btn-sm', data: {disable_with: loader, confirm: 'Are you sure want to delete this letter? '}, method: :delete %>
					<% end %>
				</div>
				<hr/>
			<% end %>						
		</div>		
		<h3><i class="fa fa-sticky-note"></i> Note</h3>
		<p>Before generate PDF for letter, Employee basic profile needs to be 100% complete. </p>

		<h3><i class="fa fa-info-circle"></i> Help</h3>
		
		<p> You can use below keywords in your letter that will replace with original value.</p>

		<ul>
			<li>
				<b>[FULL-NAME]</b>
				<p> Employee fullname </p>
			</li>
			
			<li>
				<b>[POSITION]</b> 
				<p> Employee designation</p>
			</li>
			
			<li>
				<b>[COMPANY]</b> 
				<p>Organization name (Title)</p>
			</li>
			
			<li>
				<b>[APPOINTMENT-TYPE]</b>
				<p>Employee appointment type</p>
			</li>
			
			<li>
				<b>[SUPERVISOR]</b>
				<p>Supervisor fullname </p>
			</li>

			<li>
				<b>[SUPERVISOR-POSITION]</b>
				<p>Supervisor designation</p>	
			</li>

			<li>
				<b>[JOINING-DATE]</b>
				<p>Employee joining date</p>
			</li>

			<li>
				<b>[SENDER-NAME]</b>
				<p>Sender fullname</p>
			</li>

			<li>
				<b>[SALARY]</b>
				<p>Employee salary</p>
			</li>
		</ul>
	</div>
</div>      
<div class='view-generate-pdf-form'></div>

app/views/letters/_user_info.html.erb
<% if not @employee.profile.designation.present? %>
  <div class='form-group'>
    <label>Employee Designation</label>
    <%= text_field_tag 'profile[designation]', nil, placeholder: "Designation name of employee - #{@employee.profile.fullname}", class: 'form-control' %>
  </div>

<% end %>

app/views/letters/edit.html.erb
<% content_for :title, "Edit Letter" %>
<div class='row wrapper border-bottom white-bg page-heading'>
  <div class='col-sm-6'>
    <%= show_breadcrumb('Edit Letter') %>
  </div>
</div>

<div class='row letters-list'>
	<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
    	<div class="col-lg-8">
				<div class="ibox float-e-margins">
          <div class="ibox-content">
          	<%= render 'form' %>
			  	</div>
			  </div>
    	</div>
      <div class="col-lg-4">
        <%= render partial: '/letters/help' %>
      </div>
    </div>
  </div>
</div>

app/views/letters/generate_pdf.js.erb
$(".view-generate-pdf-form").html("<%= escape_javascript(render partial: '/letters/generate_pdf') %>")
$("#view-generate-pdf-form-popup").modal({backdrop: 'static', keyboard: false})

$("#letter_employee_id").change(function(){
	$.ajax({
		url: '/letters/user_info',
		method: 'post',
		data: {employee_id: $(this).val() },
		dataType: 'script'
	})
})

$('.generate-pdf-letter-validation').validate()

app/views/letters/index.html.erb
<% content_for :title, "Letters" %>
<div class='row wrapper border-bottom white-bg page-heading'>
  <div class='col-sm-6'>
    <%= show_breadcrumb('Letters') %>
  </div>
</div>

<div class='row letters-list'>
	<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
      
      <div class="col-lg-3">
        <div class="contact-box">
        	<%= link_to new_letter_path do %>		          
            <div class="col-sm-12">
              <h3 class="truncate">
              	<strong><center>
              		<i class="fa fa-plus"></i> Add Letter
              	</center></strong>
              </h3>
            </div>
           	<div class="clearfix"></div>
          <% end %>
        </div>
      </div>

      <% if letters.present? %>
      	<% letters.each do |letter| %>
		      <div class="col-lg-3">
		        <div class="contact-box">
		        	<%= link_to letter do %>		          
		            <div class="col-sm-12">
		              <h3 class="">
		              	<strong><center>
		              		<div class='truncate'> <%= letter.title %></div>
                      <small>Updated : <%= local_time(letter.updated_at) %></small>
		              	</center></strong>
		              </h3>
		            </div>
		           	<div class="clearfix"></div>
		          <% end %>
		        </div>
		      </div>
		    <% end %>
		  <% end %>

		</div>          
  </div>	
</div>

app/views/letters/new.html.erb
<% content_for :title, "New Letter" %>
<div class='row wrapper border-bottom white-bg page-heading'>
  <div class='col-sm-6'>
    <%= show_breadcrumb('Add Letter') %>
  </div>
</div>

<div class='row letters-list'>
	<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
    	<div class="col-lg-8">
				<div class="ibox float-e-margins">
          <div class="ibox-content">
          	<%= render 'form' %>
			  	</div>
			  </div>
    	</div>
      <div class="col-lg-4">
        <%= render partial: '/letters/help' %>
      </div>
    </div>
  </div>
</div>

app/views/letters/show.html.erb
<% content_for :title, "View Letter" %>
<div class='row wrapper border-bottom white-bg page-heading'>
  <div class='col-sm-6'>
    <%= show_breadcrumb("View Letter - #{letter.title}") %>
  </div>
</div>

<div class='row letters-list'>
	<div class="wrapper wrapper-content  animated fadeInRight article">
    <div class="row">
      <div class="col-lg-8">
        <div class="ibox">
          <div class="ibox-content">
            <div class="text-center article-title">
            	<h2><%= letter.title %></h2>
            	<hr>
            	<%= letter.description.html_safe %>
            </div>
          </div>
        </div>
      </div>

      <div class="col-lg-4">
      	<%= render partial: '/letters/help' %>
      </div>
    </div>
  </div>
</div>

app/views/letters/user_info.js.erb
$(".employee-info").html("<%= escape_javascript(render partial: '/letters/user_info') %>")